### PR TITLE
bump on numpy version

### PR DESCRIPTION
**Pull request by chanokin**
changed to numpy>=1.10.0,!=1.16.*

### CODE REVIEW

**Comment by neworderofjamie** [comment]
also my machine's fucked up somehow. Will attempt to prod it into life with transatlantic ssh later

**Comment by alexdewar** [comment]
Weird... My Arch package is still building ok using Python v3.8 and numpy v1.18.1 (but not using pip): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=genn

I haven't tested whether pygenn works properly on it though. I'm happy to run any local tests you need to get it working

**Comment by neworderofjamie** [comment]
Ok, the problems on my machine are nothing to do with numpy so no need to worry about that but, @alexdewar 's machine build's master fine using numpy 1.14.6 but not this branch with numpy 1.18.1

**Comment by neworderofjamie** [comment]
Duh - pretty sure issues were because it was using the master branch of GeNN which, at that point, used an older numpy version. Now https://github.com/genn-team/genn/pull/301 has been merged, it seems to work fine so merging.

**Pull request merged**
